//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USB_CAN_Plus_Ctrl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("USB_CAN_Plus_Ctrl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося підключити адаптер USB-CAN Plus.
        /// </summary>
        internal static string AdapterConnectionError {
            get {
                return ResourceManager.GetString("AdapterConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} А.
        /// </summary>
        internal static string Apostfix {
            get {
                return ResourceManager.GetString("Apostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при запиті даних температури модуля.
        /// </summary>
        internal static string AskingAmbTempError {
            get {
                return ResourceManager.GetString("AskingAmbTempError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при запиті даних параметрів модуля {0}.
        /// </summary>
        internal static string AskingDeviceParamsError {
            get {
                return ResourceManager.GetString("AskingDeviceParamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при запиті даних фазових напруг модуля.
        /// </summary>
        internal static string AskingPhaseVoltagesError {
            get {
                return ResourceManager.GetString("AskingPhaseVoltagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підключити.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відключити.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при обробці даних параметрів модуля {0}.
        /// </summary>
        internal static string HandlingDeviceParamsError {
            get {
                return ResourceManager.GetString("HandlingDeviceParamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при обробці даних фазових напруг модуля {0}.
        /// </summary>
        internal static string HandlingPhaseVoltagesError {
            get {
                return ResourceManager.GetString("HandlingPhaseVoltagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при встановленні режиму живлення модуля.
        /// </summary>
        internal static string PoweringDeviceError {
            get {
                return ResourceManager.GetString("PoweringDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при отриманні даних температури модуля {0}.
        /// </summary>
        internal static string ReceivingAmbientTempError {
            get {
                return ResourceManager.GetString("ReceivingAmbientTempError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при отриманні даних параметрів модуля {0}.
        /// </summary>
        internal static string ReceivingDeviceParamsError {
            get {
                return ResourceManager.GetString("ReceivingDeviceParamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при отриманні даних фазових напруг модуля {0}.
        /// </summary>
        internal static string ReceivingPhaseVoltagesError {
            get {
                return ResourceManager.GetString("ReceivingPhaseVoltagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося надіслати параметри зарядки.
        /// </summary>
        internal static string SendingChargeParamsError {
            get {
                return ResourceManager.GetString("SendingChargeParamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серійний номер: {0}.
        /// </summary>
        internal static string SerialNmbActive {
            get {
                return ResourceManager.GetString("SerialNmbActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серійний номер:.
        /// </summary>
        internal static string SerialNmbInactive {
            get {
                return ResourceManager.GetString("SerialNmbInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} В.
        /// </summary>
        internal static string Vpostfix {
            get {
                return ResourceManager.GetString("Vpostfix", resourceCulture);
            }
        }
    }
}
